read -p "Enter Input File_Name: " ip
read -p "Enter Output File_Name: " op
echo Compiling...
gcc main.c
echo Running...
./a.out $ip $op
#echo Converting...
#convert op.pgm op.png
echo Deleting...
rm a.out
echo Done
